apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-${STUDENT_ID}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: zero-data-loss-upgrade
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
